# 存储表格字段

df_product_tag_pre_list = ['ASIN',
                           'site',
                           'price',
                           'category',
                           'seller_type',
                           '直发FBM可能性',
                           '预估FBA占比',
                           '预估毛利率',
                           '毛估资金利用率',
                           '开售月数',
                           '月均QA数',
                           '疑似知名品牌',
                           '疑似节日性',
                           '节日名',
                           '是否个人定制',
                           '是否翻新',
                           '推荐度',
                           '销额级数',
                           'lqs',
                           'qa',
                           'ebc_available',
                           'video_available',
                           'rating',
                           '知名品牌',
                           'variations',
                           'ratings',
                           'new_release',
                           'ac',
                           '少评好卖',
                           '二级类目',
                           '剔除类目',
                           '数据更新时间']

df_product_table_list = ['ASIN',
                         'site',
                         'sku',
                         'brand',
                         'brand_link',
                         'title',
                         'image',
                         'parent',
                         'category_path',
                         'category',
                         'category_bsr',
                         'category_bsr_growth',
                         'sub_category',
                         'sales',
                         'monthly_revenue',
                         'price',
                         # 'prime_price',
                         'qa',
                         'gross_margin',
                         'fba_fees',
                         'ratings',
                         'reviews_rate',
                         'rating',
                         'monthly_rating_increase',
                         'date_available',
                         'seller_type',
                         'lqs',
                         'variations',
                         'sellers',
                         'buybox_seller',
                         'buybox_location',
                         'buybox_type',
                         'best_seller',
                         'ac',
                         'new_release',
                         'ebc_available',
                         'video_available',
                         'ac_keyword',
                         'weight',
                         '重量(g)',
                         'dimensions',
                         'sync_time',
                         '直发FBM可能性',
                         '预估FBA占比',
                         '预估头程占比',
                         '预估货值占比',
                         '预估毛利率',
                         '毛利率级别',
                         '毛估资金利用率',
                         '开售月数',
                         '月均QA数',
                         '疑似知名品牌',
                         '疑似节日性',
                         '节日名',
                         # '疑似红海类目',
                         '销额级数',
                         '高资金利用率',
                         '高销低LQS',
                         '长期上架少Q&A',
                         '长期上架无A+',
                         '长期上架无视频',
                         '类轻小直发FBM',
                         '差评好卖',
                         '知名品牌',
                         '平均变体月销额等级',
                         '变体等级',
                         '少变体',
                         '新品爬坡快',
                         '新品增评好',
                         '新品NSR',
                         '新品AC标',
                         '少评好卖',
                         '是否个人定制',
                         '是否翻新',
                         '推荐度',
                         '二级类目',
                         '剔除类目',
                         '数据更新时间']

df_product_table_rename_dict = {'sku': 'SKU',
                                'brand': '品牌',
                                'brand_link': '品牌链接',
                                'title': '标题',
                                'image': '主图',
                                'parent': '父体',
                                'category_path': '类目路径',
                                'category': '大类目',
                                'category_bsr': '大类BSR',
                                'category_bsr_growth': '大类BSR增长率',
                                'sub_category': '小类目',
                                'sales': '月销量',
                                'monthly_revenue': '月销售额',
                                'price': '价格',
                                # 'prime_price': 'prime价格',
                                'qa': 'Q&A',
                                'gross_margin': '毛利率',
                                'fba_fees': 'FBA运费',
                                'ratings': '评分数',
                                'reviews_rate': '留评率',
                                'rating': '评分',
                                'monthly_rating_increase': '月新增评分数',
                                'date_available': '上架时间',
                                'seller_type': '配送方式',
                                'lqs': 'LQS',
                                'variations': '变体数',
                                'sellers': '卖家数',
                                'buybox_seller': 'BuyBox卖家',
                                'buybox_location': '卖家所属地',
                                'buybox_type': 'BuyBox类型',
                                'best_seller': 'Best Seller标识',
                                'ac': 'Amazon s Choice',
                                'new_release': 'New Release标识',
                                'ebc_available': 'A+页面',
                                'video_available': '视频介绍',
                                'ac_keyword': 'AC关键词',
                                'weight': '重量',
                                'dimensions': '体积',
                                'sync_time': '最近更新'}

df_product_tag_list = ['ASIN',
                       'site',
                       '价格分布',
                       'category',
                       'seller_type',
                       '直发FBM可能性',
                       '预估FBA占比分布',
                       '预估毛利率分布',
                       '毛估资金利用率分布',
                       '开售月数分布',
                       '月均QA数',
                       '疑似知名品牌',
                       '疑似节日性',
                       '节日名',
                       '推荐度分布',
                       '销额级数分布',
                       'lqs',
                       'qa',
                       'ebc_available',
                       'video_available',
                       'rating',
                       '知名品牌',
                       'variations',
                       '评分数分布',
                       'new_release',
                       'ac',
                       '少评好卖分布',
                       '是否个人定制',
                       '是否翻新',
                       '剔除类目',
                       '数据更新时间',
                       'data_id']

df_product_tag_rename_dict = {'category': '一级类目',
                              'seller_type': '配送方式分布',
                              '月均QA数': '月均QA分布',
                              'lqs': 'LQS分布',
                              'qa': 'QA分布',
                              'ebc_available': 'A+页面',
                              'video_available': '视频介绍',
                              'rating': '评分分布',
                              'variations': '变体分布',
                              'new_release': 'New Release标识',
                              'ac': 'Amazon s Choice'}

df_group_tag_pre_list = ['related_asin',
                         'site',
                         '相关竞品款数',
                         '有销额竞品款数',
                         '有销额推荐达标款数',
                         '有销额竞品款数占比',
                         '综合竞品推荐度',
                         '达标推荐度占比',
                         '推荐级别v1',
                         'TOP5月均销额',
                         'TOP5月销额',
                         '利基月GMV',
                         '价格中位数',
                         '价格集中度',
                         '预估平均毛利率',
                         '预估平均资金利用率',
                         '加权FBA运费',
                         'FBM配送占比',
                         '直发FBM产品占比',
                         '直发FBM销额占比',
                         '直发FBM月均销额',
                         'AMZ直营销额占比',
                         '大牌商标销额占比',
                         '中国卖家占比',
                         'TOP5平均LQS',
                         '冒出品平均LQS',
                         '冒出品A+占比',
                         '冒出品视频占比',
                         '冒出品QA占比',
                         '动销品平均星级',
                         '冒出品低星占比',
                         'TOP5销额占比',
                         '非TOP5销额占比',
                         '非TOP5月均销额',
                         '动销品变体中位数',
                         '平均开售月数',
                         '冒出品新品占比',
                         '新品平均月销额',
                         '平均星数',
                         '销级星数比',
                         '三标新品占比',
                         '月销增长率',
                         '加权留评率',
                         '推荐级别v2',
                         '综合投票分',
                         '综合推荐级别',
                         '数据更新时间']

df_traffic_table_list = ['related_asin',
                         'site',
                         'relevance',
                         'related_type',
                         'ASIN',
                         'sku',
                         'brand',
                         'title',
                         'image',
                         'parent',
                         'category_path',
                         'category',
                         'category_bsr',
                         'category_bsr_growth',
                         'sales',
                         'monthly_revenue',
                         'price',
                         'qa',
                         'gross_margin',
                         'fba_fees',
                         'ratings',
                         'reviews_rate',
                         'rating',
                         'monthly_rating_increase',
                         'date_available',
                         'seller_type',
                         'lqs',
                         'variations',
                         'sellers',
                         'buybox_seller',
                         'buybox_location',
                         'buybox_type',
                         'best_seller',
                         'ac',
                         'new_release',
                         'ebc_available',
                         'video_available',
                         'ac_keyword',
                         'weight',
                         '重量(g)',
                         'dimensions',
                         'update_time',
                         '直发FBM可能性',
                         '预估FBA占比',
                         '预估头程占比',
                         '预估货值占比',
                         '预估毛利率',
                         '毛利率级别',
                         '毛估资金利用率',
                         '开售月数',
                         '月均QA数',
                         '疑似知名品牌',
                         '疑似节日性',
                         '节日名',
                         '是否个人定制',
                         '是否翻新',
                         '推荐度',
                         '二级类目',
                         '剔除类目',
                         'revenue_rank',
                         '数据更新时间']

df_traffic_table_rename_dict = {'related_asin': '原ASIN',
                                'relevance': '关联度',
                                'related_type': '关联类型',
                                'sku': 'SKU',
                                'brand': '品牌',
                                'title': '标题',
                                'image': '主图',
                                'parent': '父体',
                                'category_path': '类目路径',
                                'category': '大类目',
                                'category_bsr': '大类BSR',
                                'category_bsr_growth': '大类BSR增长率',
                                'sales': '月销量',
                                'monthly_revenue': '月销售额',
                                'price': '价格',
                                'qa': 'Q&A',
                                'gross_margin': '毛利率',
                                'fba_fees': 'FBA运费',
                                'ratings': '评分数',
                                'reviews_rate': '留评率',
                                'rating': '评分',
                                'monthly_rating_increase': '月新增评分数',
                                'date_available': '上架时间',
                                'seller_type': '配送方式',
                                'lqs': 'LQS',
                                'variations': '变体数',
                                'sellers': '卖家数',
                                'buybox_seller': 'BuyBox卖家',
                                'buybox_location': '卖家所属地',
                                'buybox_type': 'BuyBox类型',
                                'best_seller': 'Best Seller标识',
                                'ac': 'Amazon s Choice',
                                'new_release': 'New Release标识',
                                'ebc_available': 'A+页面',
                                'video_available': '视频介绍',
                                'ac_keyword': 'AC关键词',
                                'weight': '重量',
                                'dimensions': '体积',
                                'update_time': '引流时间',
                                'revenue_rank': '销售额排名'}

df_group_table_list = ['related_asin',
                       'site',
                       'price',
                       'recommend',
                       '相关竞品款数',
                       '有销额竞品款数',
                       '有销额推荐达标款数',
                       '有销额竞品款数占比',
                       '综合竞品推荐度',
                       '达标推荐度占比',
                       '推荐级别v1',
                       'TOP5月均销额',
                       'TOP5月销额',
                       '利基月GMV',
                       '价格中位数',
                       '价格集中度',
                       '预估平均毛利率',
                       '预估平均资金利用率',
                       '加权FBA运费',
                       'FBM配送占比',
                       '直发FBM产品占比',
                       '直发FBM销额占比',
                       '直发FBM月均销额',
                       'blue_ocean_estimate',
                       'AMZ直营销额占比',
                       '大牌商标销额占比',
                       '中国卖家占比',
                       'TOP5平均LQS',
                       '冒出品平均LQS',
                       '冒出品A+占比',
                       '冒出品视频占比',
                       '冒出品QA占比',
                       '动销品平均星级',
                       '冒出品低星款数',
                       '冒出品低星占比',
                       'TOP5销额占比',
                       '非TOP5销额占比',
                       '非TOP5月均销额',
                       '动销品变体中位数',
                       '平均开售月数',
                       '冒出品新品占比',
                       '新品平均月销额',
                       '平均星数',
                       '销级星数比',
                       '三标新品占比',
                       '月销增长率',
                       '加权留评率',
                       'P得分',
                       'M得分',
                       'PMI得分',
                       'P标签',
                       'M标签',
                       'I标签',
                       '推荐级别v2',
                       '综合投票分',
                       '综合推荐级别',
                       '代表节点',
                       '代表度',
                       'pmi_rank',
                       'duplicate_tag',
                       'duplicate_type',
                       'asin',
                       '数据更新时间']

df_group_rename_dict = {'related_asin': '原ASIN',
                        'price': '价格',
                        'recommend': '原ASIN推荐度',
                        'blue_ocean_estimate': '广告蓝海度',
                        'duplicate_tag': '重复度',
                        'duplicate_type': '重复利基',
                        'asin': 'ASINs'}

df_group_tag_table_list = ['related_asin',
                           'site',
                           '相关竞品款数分布',
                           '有销额竞品款数分布',
                           '有销额推荐达标款数分布',
                           '有销额竞品款数占比分布',
                           '综合竞品推荐度分布',
                           '达标推荐度占比分布',
                           '推荐级别v1',
                           'TOP5月均销额分布',
                           'TOP5月销额分布',
                           '利基月GMV分布',
                           '价格中位数分布',
                           '价格集中度分布',
                           '预估平均毛利率分布',
                           '预估平均资金利用率分布',
                           '加权FBA运费分布',
                           'FBM配送占比分布',
                           '直发FBM产品占比分布',
                           '直发FBM销额占比分布',
                           '直发FBM月均销额分布',
                           'AMZ直营销额占比分布',
                           '大牌商标销额占比分布',
                           '中国卖家占比分布',
                           'TOP5平均LQS分布',
                           '冒出品平均LQS分布',
                           '冒出品A+占比分布',
                           '冒出品视频占比分布',
                           '冒出品QA占比分布',
                           '动销品平均星级分布',
                           '冒出品低星占比分布',
                           'TOP5销额占比分布',
                           '非TOP5销额占比分布',
                           '非TOP5月均销额分布',
                           '动销品变体中位数',
                           '平均开售月数分布',
                           '冒出品新品占比分布',
                           '新品平均月销额分布',
                           '平均星数分布',
                           '销级星数比分布',
                           '三标新品占比分布',
                           '月销增长率分布',
                           '加权留评率分布',
                           '推荐级别v2',
                           '综合投票分',
                           '综合推荐级别',
                           '数据更新时间',
                           'data_id']
